install.packages("shinydashboard")
install.packages("bupaR")
install.packages("eventdataR")
install.packages("xesreadR")
install.packages("edeaR")
install.packages("processmapR")
install.packages("processmonitR")
install.packages("DiagrammeR")
# install.packages(dplyr)
# install.packages(stringr)
# install.packages(readr)
install.packages("lubridate")
